version: "3.3"
services:
  app:
    build:
      args:
        user: iis
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: www
    container_name: www
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - appnet
  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - appnet
networks:
  appnet:
    driver: bridge
